/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var Analizador = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,9],$V1=[9,18],$V2=[1,20],$V3=[1,25],$V4=[1,26],$V5=[1,27],$V6=[1,28],$V7=[38,40],$V8=[23,29,30,31,32,33],$V9=[14,23,27,28,29,30,31,32,33],$Va=[1,44],$Vb=[13,39],$Vc=[1,59],$Vd=[1,58],$Ve=[23,45],$Vf=[19,23,39,45];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"archivo":3,"PALABRA_RESERVADA_WISON":4,"SIMBOLO_APERTURA":5,"PALABRA_RESERVADA_LEX":6,"BLOQUE_ABRE":7,"bloque_lex":8,"BLOQUE_CIERRA":9,"PALABRA_RESERVADA_SYNTAX":10,"DOBLE_BLOQUE_ABRE":11,"bloque_syntax":12,"DOBLE_BLOQUE_CIERRA":13,"SIMBOLO_CIERRE":14,"EOF":15,"lista_terminales":16,"declaracion_terminal":17,"PALABRA_RESERVADA_TERMINAL":18,"PALABRA_RESERVADA_DT":19,"IDENTIFICADOR":20,"FLECHA_ASIGNACION":21,"expresion_terminal":22,"PUNTO_Y_COMA":23,"concatenacion":24,"repeticion":25,"base":26,"KLEENE":27,"MAS":28,"TEXTO":29,"RANGO_LETRAS":30,"RANGO_NUMEROS":31,"PARENTESIS_ABRE":32,"PARENTESIS_CIERRA":33,"lista_no_terminales":34,"simbolo_inicial":35,"lista_producciones":36,"declaracion_no_terminal":37,"PALABRA_RESERVADA_NO_TERMINAL":38,"PALABRA_RESERVADA_DNT":39,"PALABRA_RESERVADA_INITIAL_SIM":40,"produccion":41,"lado_izq":42,"FLECHA_PRODUCCION":43,"lado_der":44,"OR":45,"secuencia":46,"simbolo":47,"$accept":0,"$end":1},
terminals_: {2:"error",4:"PALABRA_RESERVADA_WISON",5:"SIMBOLO_APERTURA",6:"PALABRA_RESERVADA_LEX",7:"BLOQUE_ABRE",9:"BLOQUE_CIERRA",10:"PALABRA_RESERVADA_SYNTAX",11:"DOBLE_BLOQUE_ABRE",13:"DOBLE_BLOQUE_CIERRA",14:"SIMBOLO_CIERRE",15:"EOF",18:"PALABRA_RESERVADA_TERMINAL",19:"PALABRA_RESERVADA_DT",20:"IDENTIFICADOR",21:"FLECHA_ASIGNACION",23:"PUNTO_Y_COMA",27:"KLEENE",28:"MAS",29:"TEXTO",30:"RANGO_LETRAS",31:"RANGO_NUMEROS",32:"PARENTESIS_ABRE",33:"PARENTESIS_CIERRA",38:"PALABRA_RESERVADA_NO_TERMINAL",39:"PALABRA_RESERVADA_DNT",40:"PALABRA_RESERVADA_INITIAL_SIM",43:"FLECHA_PRODUCCION",45:"OR"},
productions_: [0,[3,13],[8,1],[16,2],[16,1],[17,6],[22,1],[24,2],[24,1],[25,1],[25,2],[25,2],[25,2],[26,1],[26,1],[26,1],[26,3],[12,3],[34,2],[34,1],[37,4],[35,4],[36,2],[36,1],[41,4],[42,2],[44,3],[44,1],[46,2],[46,1],[47,2],[47,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:[1,3]},{6:[1,4]},{7:[1,5]},{8:6,16:7,17:8,18:$V0},{9:[1,10]},{9:[2,2],17:11,18:$V0},o($V1,[2,4]),{19:[1,12]},{10:[1,13]},o($V1,[2,3]),{20:[1,14]},{11:[1,15]},{21:[1,16]},{12:17,34:18,37:19,38:$V2},{22:21,24:22,25:23,26:24,29:$V3,30:$V4,31:$V5,32:$V6},{13:[1,29]},{35:30,37:31,38:$V2,40:[1,32]},o($V7,[2,19]),{39:[1,33]},{23:[1,34]},o([23,33],[2,6],{26:24,25:35,29:$V3,30:$V4,31:$V5,32:$V6}),o($V8,[2,8]),o($V8,[2,9],{14:[1,38],27:[1,36],28:[1,37]}),o($V9,[2,13]),o($V9,[2,14]),o($V9,[2,15]),{22:39,24:22,25:23,26:24,29:$V3,30:$V4,31:$V5,32:$V6},{14:[1,40]},{36:41,39:$Va,41:42,42:43},o($V7,[2,18]),{39:[1,45]},{20:[1,46]},o($V1,[2,5]),o($V8,[2,7]),o($V8,[2,10]),o($V8,[2,11]),o($V8,[2,12]),{33:[1,47]},{4:[1,48]},{13:[2,17],39:$Va,41:49,42:43},o($Vb,[2,23]),{43:[1,50]},{20:[1,51]},{20:[1,52]},{23:[1,53]},o($V9,[2,16]),{15:[1,54]},o($Vb,[2,22]),{19:$Vc,39:$Vd,44:55,46:56,47:57},{43:[2,25]},{23:[1,60]},o($V7,[2,20]),{1:[2,1]},{23:[1,61],45:[1,62]},o($Ve,[2,27],{47:63,19:$Vc,39:$Vd}),o($Vf,[2,29]),{20:[1,64]},{20:[1,65]},{39:[2,21]},o($Vb,[2,24]),{19:$Vc,39:$Vd,46:66,47:57},o($Vf,[2,28]),o($Vf,[2,30]),o($Vf,[2,31]),o($Ve,[2,26],{47:63,19:$Vc,39:$Vd})],
defaultActions: {51:[2,25],54:[2,1],60:[2,21]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignorar espacios, tabs y saltos */
break;
case 1:/* comentario de una linea */
break;
case 2:/* comentario multilinea */
break;
case 3:return 4;
break;
case 4:return 6;
break;
case 5:return 10;
break;
case 6:return 18;
break;
case 7:return 38;
break;
case 8:return 40;
break;
case 9:return 11;
break;
case 10:return 13;
break;
case 11:return 7;
break;
case 12:return 9;
break;
case 13:return 19;
break;
case 14:return 39;    
break;
case 15:return 5;
break;
case 16:return 14;
break;
case 17:return 'LLAVE_ABRE';
break;
case 18:return 'LLAVE_CIERRA';
break;
case 19:return 32;
break;
case 20:return 33;
break;
case 21:return 'CORCHETE_ABRE';
break;
case 22:return 'CORCHETE_CIERRA';
break;
case 23:return 'DOS_PUNTOS';
break;
case 24:return 23;
break;
case 25:return 'COMA';
break;
case 26:return 21;
break;
case 27:return 43;
break;
case 28:return 'IGUAL';
break;
case 29:return 45;
break;
case 30:return 27;
break;
case 31:return 28;
break;
case 32:return 30;
break;
case 33:return 31;
break;
case 34:return 29;
break;
case 35:return 20;
break;
case 36:return 'ERROR';
break;
case 37:return 15;
break;
}
},
rules: [/^(?:[ \t\r\n]+)/,/^(?:\/.*)/,/^(?:\/\*\*[^]*?\*\/)/,/^(?:Wison\b)/,/^(?:Lex\b)/,/^(?:Syntax\b)/,/^(?:Terminal\b)/,/^(?:No_Terminal\b)/,/^(?:Initial_Sim\b)/,/^(?:\{\{:)/,/^(?::\}\})/,/^(?::\{)/,/^(?::\})/,/^(?:\$)/,/^(?:%)/,/^(?:¿)/,/^(?:\?)/,/^(?:\{)/,/^(?:\})/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?::)/,/^(?:;)/,/^(?:,)/,/^(?:<-)/,/^(?:<=)/,/^(?:=)/,/^(?:\|)/,/^(?:\*)/,/^(?:\+)/,/^(?:\[aA-zZ\])/,/^(?:\[0-9\])/,/^(?:'[^\']*')/,/^(?:_[a-zA-Z0-9_]*)/,/^(?:.)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = Analizador;
exports.Parser = Analizador.Parser;
exports.parse = function () { return Analizador.parse.apply(Analizador, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}